name: Generate Contribution Snake

on:
  repository_dispatch:
    types: [profile_update]
  workflow_dispatch:
  schedule:`r`n    - cron: "*/5 * * * *"
  push:
    branches:
      - main
    paths-ignore:
      - "profile/streak.svg"

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Generate contribution snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-blue.svg?color_snake=%2300B7FF&color_dots=%230B1220,%23112A46,%231A4D73,%230078B8,%2300B7FF

      - name: Publish generated files
        uses: crazy-max/ghaction-github-pages@v5
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

